import type { Metadata } from "next";
import "./globals.css";
import "./globalicon.css";
import "./reset.css";

export const metadata: Metadata = {
  title: "Yoonstar's portfolio",
  description: "Generated by Yoonstar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
